// NOTE: This is here instead of include/ because love includes <../config.h>...

#   define LOVE_SORVI

#	define LOVE_ENABLE_LOVE
#	define LOVE_ENABLE_AUDIO
#	define LOVE_ENABLE_DATA
#	define LOVE_ENABLE_EVENT
#	define LOVE_ENABLE_FILESYSTEM
#	define LOVE_ENABLE_FONT
#	define LOVE_ENABLE_GRAPHICS
#	define LOVE_ENABLE_IMAGE
#	define LOVE_ENABLE_JOYSTICK
#	define LOVE_ENABLE_KEYBOARD
#	define LOVE_ENABLE_MATH
#	define LOVE_ENABLE_MOUSE
#	define LOVE_ENABLE_PHYSICS
#	define LOVE_ENABLE_SENSOR
#	define LOVE_ENABLE_SOUND
#	define LOVE_ENABLE_SYSTEM
#	define LOVE_ENABLE_THREAD
#	define LOVE_ENABLE_TIMER
#	define LOVE_ENABLE_TOUCH
#	define LOVE_ENABLE_VIDEO
#	define LOVE_ENABLE_WINDOW

#	define LOVE_ENABLE_LUA53
// #	define LOVE_ENABLE_ENET
// #	define LOVE_ENABLE_LUASOCKET
// #	define LOVE_ENABLE_LUAHTTPS

#	define LOVE_BUILD
#	define LOVE_BUILD_STANDALONE
#	define LOVE_BUILD_EXE
